name: Build Custom Kairos Image with custom Dockerfile

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' 

permissions:
  actions: write
  contents: write
  security-events: write
  id-token: write

jobs:
  delete-old-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old artifacts
        run: |
          gh api repos/${{ github.repository }}/actions/artifacts --jq ".artifacts[].id" | xargs -I {} gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/{}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # build-arm64:
  #   uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@main
  #   secrets:
  #     registry_username: ${{ secrets.REGISTRY_USERNAME }}
  #     registry_password: ${{ secrets.REGISTRY_PASSWORD }}
  #   with:
  #     version: "auto"
  #     model: "generic"
  #     arch: "arm64"
  #     base_image: "ubuntu:24.04"
  #     kubernetes_distro: "k0s"
  #     kubernetes_version: "v1.32.8+k0s.0"
  #     registry_domain: "ghcr.io"
  #     registry_namespace: "paranoiasystem"
  #     registry_repository: "homelab/kairos"
  #     dockerfile_path: "custom/Dockerfile"
  #     raw: true
  #     summary_artifacts: true

  build-arm64-rpi4:
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@v0.0.9
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
    with:
      version: "auto"
      model: "rpi4"
      arch: "arm64"
      base_image: debian:12
      kubernetes_distro: "k0s"
      kubernetes_version: "v1.32.8+k0s.0"
      registry_domain: "ghcr.io"
      registry_namespace: "paranoiasystem"
      registry_repository: "homelab/kairos"
      dockerfile_path: "custom/Dockerfile"
      raw: true
      summary_artifacts: true

  # build-amd64:
  #   uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@main
  #   secrets:
  #     registry_username: ${{ secrets.REGISTRY_USERNAME }}
  #     registry_password: ${{ secrets.REGISTRY_PASSWORD }}
  #   with:
  #     version: "auto"
  #     model: "generic"
  #     arch: "amd64"
  #     base_image: "ubuntu:24.04"
  #     kubernetes_distro: "k0s"
  #     kubernetes_version: "v1.32.8+k0s.0"
  #     registry_domain: "ghcr.io"
  #     registry_namespace: "paranoiasystem"
  #     registry_repository: "homelab/kairos"
  #     dockerfile_path: "custom/Dockerfile"
  #     iso: true
  #     raw: true
  #     summary_artifacts: true